apiVersion: apps/v1
kind: Deployment
metadata:
 name: crm-svc-deploy
 namespace: bookstore-ns
spec:
 selector:
  matchLabels:
   app: crm-ms
 replicas: 1
 template:
  metadata:
   labels:
    app: crm-ms
  spec:
   containers:
    - name: crm-ms
      image: juancarv/cmu-a3-crm:v1
      ports:
       - containerPort: 8081